baseurl: https://eis1600.github.io
languageCode: en-us
theme: "hugo-theme-stack"
paginate: 5
title: Evolution of Islamic Societies (c. 600-1600)

languages:
    en:
        languageName: English
        title: "The Evolution of Islamic Societies (c. 600-1600 CE)"
        weight: 1
        params:
            description: "Emmy Noether Junior Research Group • DFG • Universität Hamburg"
            footer:
                text: "“The Evolution of Islamic Societies (c.600-1600 CE): Algorithmic Analysis into Social History” • Emmy Noether Junior Research Group • DFG • Universität Hamburg, Afrika-Asien Institut • Team: Hamid Reza Hakimi, PhD Researcher • Lisa Mischer, PhD Researcher • Tariq Yousef, CS Researcher • Maxim Romanov, PI<br>"
            sidebar:
                emoji: ~
                avatar:
                    enabled: true
                    local: true
                    src: img/eis1600_SMALL_mix_blue_white.png
    de:
        languageName: Deutsch
        title: "Die Entwicklung islamischer Gesellschaften (ca. 600–1600)"
        weight: 2
        params:
            description: "Emmy Noether Nachwuchsgruppe • DFG • Universität Hamburg"
            footer:
                text: "«Die Entwicklung islamischer Gesellschaften (ca. 600–1600): algorithmische Analyse zur Sozialgeschichte» • Emmy Noether Nachwuchsgruppe • DFG • Universität Hamburg, Afrika-Asien Institut • Team: Hamid Reza Hakimi, wiss. Mitarbeiter • Lisa Mischer, wiss. Mitarbeiterin • Tariq Yousef, wiss. Mitarbeiter • Maxim Romanov, Nachwuchsgruppenleiter<br>"
            sidebar:
                emoji: false
                avatar:
                    enabled: true
                    local: true
                    src: img/eis1600_SMALL_mix_red_white.png
    ru:
        languageName: Русский
        title: "Эволюция мусульманских сообществ (600-1600 гг. н.э.)"
        weight: 3
        params:
            description: "Исследовательская группа в рамках программы «Эмми Нётер» • Немецкий исследовательский фонд (DFG) • Гамбургский университет"
            footer:
                since: 2022
                text: "«Эволюция мусульманских сообществ (ок. 600-1600 гг. н.э.): через алгоритмический анализ к социальной истории» • Исследовательская группа в рамках программы «Эмми Нётер» • Немецкий исследовательский фонд (DFG) • Гамбургский университет • Институт Африки и Азии • Состав • Хамид-Реза Хакими, исследователь-аспирант • Лиза Мишер, исследовательница-аспирантка • Тарик Йусуф, исследователь-специалист по информатике • Максим Романов, руководитель исследовательской группы <br>"
            sidebar:
                emoji: false
                avatar:
                    enabled: true
                    local: true
                    src: img/eis1600_SMALL_mix_grey_white.png
    ar:
        languageName: عربي
        languagedirection: rtl
        title: "تطور المجتمعات الإسلامية (بين ٦٠٠ و ١٦٠٠ للميلاد)"
        weight: 4
        params:
            description: "• مجموعة إيمي نوتر الفتية للأبحاث • مؤسسة الأبحاث الألمانية •  جامعة هامبورغ"
            footer:
                text: "«تطور المجتمعات الإسلامية (بين ٦٠٠ و ١٦٠٠ للميلاد): من التحليل الحوسبي إلى التاريخ الاجتماعي» • مجموعة إيمي نوتر الفتية للأبحاث • مؤسسة الأبحاث الألمانية •  جامعة هامبورغ • معهد آسيا وأفريقا • فريق العمل • حميد رضا حكيمي، باحث دكتوراه • ليزا ميشر، باحثة دكتوراه • طارق يوسف، باحث علوم حاسب • مكسيم رومانوف، الباحث الرئيسي <br>"
            sidebar:
                emoji: false
                avatar:
                    enabled: true
                    local: true
                    src: img/eis1600_SMALL_mix_green_white.png
    fa:
        languageName: فارسى
        languagedirection: rtl
        title: "تکامل جوامع اسلامی (۱۶۰۰-۶۰۰ م)"
        weight: 5
        params:
            description: "گروه پژوهشی امی-نوتر • بنیاد پژوهشی آلمان • دانشگاه هامبورگ"
            footer:
                text: "«تکامل جوامع اسلامی (۱۶۰۰-۶۰۰ م): از تحلیل الگوریتمی تا تاریخ اجتماعی» • گروه پژوهشی امی-نوتر • بنیاد پژوهشی آلمان • دانشگاه هامبورگ • مؤسسه‌ی آسیا-آفریقا • اعضای تیم • حمیدرضا حکیمی، پژوهشگر دکتری • لیزا میشر، پژوهشگر دکتری • طارق یوسف، پژوهشگر علوم رایانه • مکسیم رومانوف، پژوهشگر ارشد • <br>"
            sidebar:
                emoji: false
                avatar:
                    enabled: true
                    local: true
                    src: img/eis1600_SMALL_mix_turquoise_white.png


# Change it to your Disqus shortname before using
disqusShortname:

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:  # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)

    footer:
        since: 2022

    dateFormat:
        published:
        lastUpdated: January 02, 2020

    sidebar:
        emoji: false
        subtitle: "Emmy Noether Junior Research Group • DFG • Universität Hamburg, Afrika-Asien Institut • Team: Hamid Reza Hakimi, PhD Researcher • Lisa Mischer, PhD Researcher • Tariq Yousef, CS Researcher • Maxim Romanov, PI"
        avatar:
            enabled: true
            local: true
            src: img/eis1600_SMALL_mix_blue_white.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/component.html
        waline:
            serverURL:
            lang:
            pageview:
            emoji:
                - https://unpkg.com/@waline/emojis@1.0.1/weibo
            requiredMeta:
                - name
                - email
                - url
            locale:
                admin: Admin
                placeholder:

        twikoo:
            envId:
            region:
            path:
            lang:

        # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
        cactus:
            defaultHomeserverUrl:
            serverName:
            siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:
    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: []

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/EIS1600/
          params:
              icon: brand-github

        - identifier: instagram
          name: Instagram
          url: https://www.instagram.com/eis1600project/
          params:
              icon: brand-instagram

        - identifier: twitter
          name: Twitter
          url: https://twitter.com/eis1600project
          params:
              icon: brand-twitter

        - identifier: facebook
          name: Facebook
          url: https://www.facebook.com/people/EIS1600Project/100087679731197/
          params:
              icon: brand-facebook

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
